# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: image_enhance.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13image_enhance.proto\x12\rimage_enhance\"M\n\x0cImageRequest\x12\x12\n\nimage_data\x18\x01 \x01(\x0c\x12\x13\n\x0bimage_width\x18\x02 \x01(\x05\x12\x14\n\x0cimage_height\x18\x03 \x01(\x05\"\'\n\x14ImagePatchesResponse\x12\x0f\n\x07patches\x18\x01 \x03(\x0c\"+\n\x13MergedImageResponse\x12\x14\n\x0cmerged_image\x18\x01 \x01(\x0c\x32\xb8\x01\n\x15ImageProcessorService\x12N\n\nSplitImage\x12\x1b.image_enhance.ImageRequest\x1a#.image_enhance.ImagePatchesResponse\x12O\n\x0cMergePatches\x12\".image_enhance.MergedImageResponse\x1a\x1b.image_enhance.ImageRequestb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'image_enhance_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_IMAGEREQUEST']._serialized_start=38
  _globals['_IMAGEREQUEST']._serialized_end=115
  _globals['_IMAGEPATCHESRESPONSE']._serialized_start=117
  _globals['_IMAGEPATCHESRESPONSE']._serialized_end=156
  _globals['_MERGEDIMAGERESPONSE']._serialized_start=158
  _globals['_MERGEDIMAGERESPONSE']._serialized_end=201
  _globals['_IMAGEPROCESSORSERVICE']._serialized_start=204
  _globals['_IMAGEPROCESSORSERVICE']._serialized_end=388
# @@protoc_insertion_point(module_scope)
