# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import image_enhance_pb2 as image__enhance__pb2


class ImageEnhancerStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.EnhanceImage = channel.unary_unary(
                '/ImageEnhancer/EnhanceImage',
                request_serializer=image__enhance__pb2.ImageRequest.SerializeToString,
                response_deserializer=image__enhance__pb2.ImageResponse.FromString,
                )


class ImageEnhancerServicer(object):
    """Missing associated documentation comment in .proto file."""

    def EnhanceImage(self, request, context):
        """Enhance the image
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ImageEnhancerServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'EnhanceImage': grpc.unary_unary_rpc_method_handler(
                    servicer.EnhanceImage,
                    request_deserializer=image__enhance__pb2.ImageRequest.FromString,
                    response_serializer=image__enhance__pb2.ImageResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ImageEnhancer', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ImageEnhancer(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def EnhanceImage(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/ImageEnhancer/EnhanceImage',
            image__enhance__pb2.ImageRequest.SerializeToString,
            image__enhance__pb2.ImageResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
