# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: math.proto
# Protobuf Python Version: 4.25.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nmath.proto\x12\x05trial\"#\n\x0bMathRequest\x12\t\n\x01\x61\x18\x01 \x01(\x05\x12\t\n\x01\x62\x18\x02 \x01(\x05\"\x1e\n\x0cMathResponse\x12\x0e\n\x06result\x18\x01 \x01(\x02\x32\xa7\x02\n\x0bMathService\x12\x35\n\x08\x41\x64\x64ition\x12\x12.trial.MathRequest\x1a\x13.trial.MathResponse\"\x00\x12\x39\n\x0cSubstraction\x12\x12.trial.MathRequest\x1a\x13.trial.MathResponse\"\x00\x12;\n\x0eMultiplication\x12\x12.trial.MathRequest\x1a\x13.trial.MathResponse\"\x00\x12\x35\n\x08\x44ivision\x12\x12.trial.MathRequest\x1a\x13.trial.MathResponse\"\x00\x12\x32\n\x05Power\x12\x12.trial.MathRequest\x1a\x13.trial.MathResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'math_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  DESCRIPTOR._options = None
  _globals['_MATHREQUEST']._serialized_start=21
  _globals['_MATHREQUEST']._serialized_end=56
  _globals['_MATHRESPONSE']._serialized_start=58
  _globals['_MATHRESPONSE']._serialized_end=88
  _globals['_MATHSERVICE']._serialized_start=91
  _globals['_MATHSERVICE']._serialized_end=386
# @@protoc_insertion_point(module_scope)
